package Utilities;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestSampleTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		WebDriverManager.chromedriver().setup();
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void testSample() throws Exception {
		driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
		Thread.sleep(3000);
		driver.manage().window().setSize(new Dimension(987, 585));
		driver.findElement(By.name("username")).click();
		Thread.sleep(3000);
		driver.findElement(By.name("username")).sendKeys("Admin");
		Thread.sleep(3000);
		driver.findElement(By.name("password")).sendKeys("admin123");
		Thread.sleep(3000);
		driver.findElement(By.cssSelector(".oxd-button")).click();
		Thread.sleep(3000);
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".oxd-text--h6"));
			assert (elements.size() > 0);
			//Thread.sleep(3000);
		}
		Thread.sleep(3000);
		assertThat(driver.findElement(By.cssSelector(".oxd-text--h6")).getText(), is("Dashboard"));
		Thread.sleep(3000);
		driver.findElement(By.cssSelector(".oxd-userdropdown-name")).click();
		Thread.sleep(3000);
		driver.findElement(By.linkText("Logout")).click();
		Thread.sleep(3000);
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".orangehrm-login-forgot-header"));
			assert (elements.size() > 0);
		}
		Thread.sleep(3000);
		assertThat(driver.findElement(By.cssSelector(".orangehrm-login-forgot-header")).getText(),
				is("Forgot your Password?"));
	}
}
